// AUTO-GENERATED by generate_rand_const.py
// DO NOT EDIT MANUALLY

#ifndef RAND_CONST_H
#define RAND_CONST_H

#include <map>
#include <string>
#include <utility> // for std::pair

struct RandConstraints {
    // Declaration only
    static std::map<std::string, std::pair<double, double>> constraints;
};

#endif // RAND_CONST_H
