// AUTO-GENERATED by generate_rand_const.py
// DO NOT EDIT MANUALLY

#include "rand_const.h"

// Definition: only once in the entire program
std::map<std::string, std::pair<double, double>> RandConstraints::constraints = {

};
